### ISSUE TITLE
C++ exceptions from AUTO take down the entire process

### ISSUE THREAD

**Issue by BenNordick** [sys-bio/rrplugins#32]
The AUTO code contains several throw statements that throw string literals, i.e. instances of `char const*`, perhaps most notably [this one](https://github.com/sys-bio/rrplugins/blob/master/plugins/released/auto2000/libAuto/autlib1.cpp#L4426-L4430) when something goes to zero during Gaussian elimination. The wrapper has [a catch block](https://github.com/sys-bio/rrplugins/blob/master/plugins/released/auto2000/libAuto/vsAuto.cpp#L339-L344), but it only catches `std::exception` instances, so thrown `char const*`s go unhandled and cause the entire process to terminate. This is problematic for Python scripts that invoke the plugin several times to test different scenarios. It would be ideal if AUTO exceptions were exposed in such a way that non-C++ code could react to them.

**Comment by luciansmith** [comment]
Thank you for this!  I've checked in a fix that I think should work:

https://github.com/sys-bio/roadrunner/pull/805/files

but I don't have anything to test it on.  I'm happy to try this myself if you can provide (or describe) an example, or we can provide you a binary so that you can test it yourself if you tell me what platform you're using.

**Comment by BenNordick** [comment]
Thank you! I downloaded the latest artifact from Azure Pipelines and was able to juggle SO files to install it in my Python environment. The script can now continue even if one AUTO run crashes.

I hadn't noticed that rrplugins development is now in the main roadrunner repository, sorry. I will report any future issues there. Thanks again.

**Comment by luciansmith** [comment]
Great!  And either place works to report issues, I think--we've only just switched over to recombine the two projects.
